blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import ( login_view, register_view, logout_view)
from posts.views import (grafana)
# from posts import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls",namespace = "comments")),
    url(r'^login/',login_view,name='login'),
    url(r'^logout/',logout_view,name='logout'),
    url(r'^register/',register_view,name='register'),
    url(r'^grafana/', grafana,name='grafana'),
    url(r'^api/users/', include("accounts.api.urls",namespace = "users_api")),
    url(r'^api/comments/', include("comments.api.urls",namespace = "comments_api")),
    url(r'^api/posts/', include("posts.api.urls",namespace = "posts_api")),
    url(r'^', include("posts.urls",namespace = "posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/api/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts.api.views import ( PostListAPIView, PostDetailAPIView,
							 PostUpdateAPIView, PostDeleteAPIView,
							 PostCreateAPIView )

urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name='list' ),
    # url(r'^table/$', views.table, name='table' ),
    url(r'^create/$', PostCreateAPIView.as_view(),name="create" ),
    url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteAPIView.as_view(), name="delete" ),
    url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateAPIView.as_view() , name="update"),
    url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(),name="detail" ),
]

posts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.list, name='list' ),
    url(r'^table/$', views.table, name='table' ),
    url(r'^create/$', views.create,name="create" ),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.delete, name="delete" ),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.update , name="update"),
    url(r'^(?P<slug>[\w-]+)/$', views.detail,name="detail" ),
]

posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from django.utils import timezone
from django.utils.safestring import mark_safe
from markdown_deux import markdown
from comments.models import Comment
from django.contrib.contenttypes.models import ContentType
from .utils import get_read_time
# Create your models here.

class PostManager(models.Manager):
	def active(self,*args,**kwargs):
		return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


class Post(models.Model):
	"""Model for Post"""
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default= 1)
	title = models.CharField(max_length = 120)
	content = models.TextField()
	slug = models.SlugField(unique = True)
	draft = models.BooleanField(default= False)
	publish = models.DateField(auto_now= False,auto_now_add = False)
	image = models.ImageField(null = True, blank = True,height_field="height_field",width_field="width_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	updated = models.DateTimeField(auto_now = True, auto_now_add = False)
	timestamp = models.DateTimeField(auto_now = False, auto_now_add = True)
	read_time = models.IntegerField(null=True) #models.TimeField(null=True, blank=True)

	objects = PostManager()
	def __str__(self):
		return self.title

	def __unicode__(self):
		return self.title

	def get_abs_url(self):
		return reverse("posts:detail",kwargs = {"slug":self.slug})

	def get_api_url(self):
		return reverse("posts_api:detail",kwargs = {"slug":self.slug})

	def get_abs_editurl(self):
		return reverse("posts:update",kwargs = {"slug":self.slug})

	def get_abs_deleteurl(self):
		return reverse("posts:delete",kwargs = {"slug":self.slug})
		# return "/posts/%s" %(self.id)
	def get_markdown(self):
		print('calling markdown')
		content = self.content
		markdown_text = markdown(content)
		return mark_safe(markdown_text)

	@property
	def comments(self):
		instance = self
		qs = Comment.objects.filter_by_instance(instance)
		return qs

	@property
	def get_content_type(self):
		instance = self
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type

	class Meta:
		ordering = ["-timestamp","-updated"]

def create_slug(instance, new_slug= None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Post.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
	# slug = slugify(instance.title)
	# exists = Post.objects.filter(slug=slug).exists()
	# if exists:
	# 	slug = "%s-%s" %(slugify(instance.title), instance.id)
	# instance.slug = slug
	if not instance.slug:
		instance.slug = create_slug(instance)
	if instance.content:
		html_str= instance.get_markdown()
		count = get_read_time(html_str)
		instance.read_time = count
		print(count)
		print("hii")

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms
from .models import Post
from pagedown.widgets import PagedownWidget

class PostForm(forms.ModelForm):
	"""docstring for PostForm"""
	publish = forms.DateField(widget= forms.SelectDateWidget)
	content = forms.CharField(widget= PagedownWidget(show_preview=False))
	class Meta:
		"""docstring for Meta"""
		model = Post
		fields = ["title","content","image","draft","publish"]
			

posts/api/views.py
from django.db.models import Q
from rest_framework.generics import  ( ListAPIView, RetrieveAPIView,
									 UpdateAPIView, DestroyAPIView,
									 CreateAPIView, RetrieveUpdateAPIView )
from rest_framework.filters import ( SearchFilter, OrderingFilter)
from .pagination import (PostLimitOffsetPagination, PostPageNumberPagination)
from posts.models import Post
from .permissions import IsOwnerOrReadOnly
from rest_framework.permissions import ( AllowAny, IsAuthenticated,
										IsAdminUser, IsAuthenticatedOrReadOnly )
from .serializers import ( PostListSerializer, PostDetailSerializer,
							 PostCreateUpdateSerializer )


class PostCreateAPIView(CreateAPIView):
	queryset = Post.objects.all()
	serializer_class = PostCreateUpdateSerializer
	permission_classes = [IsAuthenticated]

	def perform_create(self,serializer):
		serializer.save(user=self.request.user)

class PostListAPIView(ListAPIView):
	# queryset = Post.objects.all()
	serializer_class = PostListSerializer
	filter_backends= [SearchFilter]
	search_fields = ('title','content','user__first_name')
	pagination_class = PostLimitOffsetPagination #PageNumberPagination

	def get_queryset(self,*args,**kwargs):
		queryset_list = Post.objects.all()
		query = self.request.GET.get("q")
		if query:
			queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query)|
				Q(user__last_name__icontains=query)
				).distinct()
		return queryset_list

class PostDetailAPIView(RetrieveAPIView):
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer
	lookup_field = 'slug'

class PostUpdateAPIView(RetrieveUpdateAPIView):
	queryset = Post.objects.all()
	serializer_class = PostCreateUpdateSerializer
	permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
	lookup_field = 'slug'

class PostDeleteAPIView(DestroyAPIView):
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer
	lookup_field = 'slug'

posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from urllib import quote_plus
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from django.utils import timezone
from .forms import PostForm
from django.db.models import Q
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from comments.models import Comment
from comments.forms import CommentForm
from .utils import get_read_time
# Create your views here.

def grafana(request):
	return render(request,"grafana.html")
	
def create(request):
	if not request.user.is_superuser or not request.user.is_staff:
		raise Http404
	if not request.user.is_authenticated():
		raise Http404
	form = PostForm(request.POST or None, request.FILES or None)
	if request.method == "POST":
		if form.is_valid():
			title = form.cleaned_data['title']
			content = form.cleaned_data['content']
			instance = form.save(commit=False)
			instance.user = request.user
			instance.save()
			messages.success(request,"Successfully Created")
			return HttpResponseRedirect(instance.get_abs_url())
		else:
			print("else")
			messages.error(request,"Not Successfully Created")
	context = {
	"form": form,
	}
	return render(request,"post_form.html",context)

def detail(request,slug):
	instance = get_object_or_404(Post, slug=slug)
	if instance.draft or instance.publish > timezone.now().date():
		if not request.user.is_superuser or not request.user.is_staff:
			raise Http404
	share_str = quote_plus(instance.content.encode('utf-8'))
	print(get_read_time(instance.get_markdown()))
	initial_data = {
					"content_type":instance.get_content_type,
					"object_id": instance.id
					}
	form = CommentForm(request.POST or None, initial = initial_data)
	if form.is_valid() and request.user.is_authenticated():
		c_type = form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		parent_obj = None
		try:
			print(form.cleaned_data)
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None
		print(parent_id)
		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()

		obj_id = form.cleaned_data.get('object_id')
		content_data = form.cleaned_data.get("content")
		new_comment, created = Comment.objects.get_or_create(
													user=request.user,
													content_type=content_type,
													object_id=obj_id,
													content=content_data,
													parent=parent_obj
												)
		if created:
			print("yeah it worked")
			print(created)
		return HttpResponseRedirect(new_comment.content_object.get_abs_url())
		

	comments = instance.comments
	context = {
	"title" : instance.title,
	"obj": instance,
	"share_str": share_str,
	"comments": comments,
	"comment_form":form
	}
	return render(request,"post_detail.html",context)

def list(request):
	allobj_list = Post.objects.active() #.order_by("-timestamp")
	if request.user.is_superuser or request.user.is_staff:
		allobj_list = Post.objects.all()
	if request.method == "GET":
		query = request.GET.get("q")
		if query:
			allobj_list = allobj_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query)|
				Q(user__last_name__icontains=query)
				).distinct()
	paginator = Paginator(allobj_list, 6) # Show 25 contacts per page
	page_request_var = 'page'
	page = request.GET.get(page_request_var)
	try:
		allobj = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		allobj = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		allobj = paginator.page(paginator.num_pages)
	today = timezone.now().date()
	context = {
	"allobj":allobj,
	"title" : "Posts",
	"page" : page_request_var,
	"today" : today
	}
	# if request.user.is_authenticated():
	# 	context = {
	# 	"title" : "My List"
	# 	}
	# else:
	# 	context = {
	# 	"title" : "List"
	# 	}
	return render(request,"post_list.html",context)

def update(request,slug = None):
	if not request.user.is_superuser or not request.user.is_staff:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None , instance=instance)
	if request.method == "POST":
		if form.is_valid():
			instance = form.save(commit=False)
			instance.save()
			messages.success(request,"Successfully Saved")
			return HttpResponseRedirect(instance.get_abs_url())
		else:
			messages.error(request,"Failed Saving")
	context = {
	"title" : instance.title,
	"obj": instance,
	"form":form,
	}
	return render(request,"post_form.html",context)

def delete(request, slug=None):
	instance = get_object_or_404(Post,slug=slug)
	instance.delete()
	messages.success(request,"Item Deleted")
	return redirect("posts:list")

def table(request):
	return render(request,'table.html')

templates/base.html
{% load staticfiles %}
<!--DocType-->
<!DOCTYPE html>
<html>
<head>
	<title>{% block head_title%} My Blog {% endblock head_title%}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- <script type="text/javascript">
		document.addEventListener('contextmenu', function(e) {
		  e.preventDefault();
		});
		document.onkeydown = function(e) {
		  if(event.keyCode == 123) {
		     return false;
		  }
		  if(e.ctrlKey && e.shiftKey && e.keyCode == 'I'.charCodeAt(0)) {
		     return false;
		  }
		  if(e.ctrlKey && e.shiftKey && e.keyCode == 'C'.charCodeAt(0)) {
		     return false;
		  }
		  if(e.ctrlKey && e.shiftKey && e.keyCode == 'J'.charCodeAt(0)) {
		     return false;
		  }
		  if(e.ctrlKey && e.keyCode == 'U'.charCodeAt(0)) {
		     return false;
		  }
		}
	</script> -->
	{% block head_extra %} {% endblock head_extra %}
</head>
<body>
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2';
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>

	{% include "message_display.html" %}
	<div class="container">
		<nav class="navbar  navbar-expand-lg navbar-dark bg-dark">
			<div class="navbar-nav col-md-12">
				<div class="nav-item col-md-1 {% block active %}{% endblock active %}"><a class="nav-link" href="{% url 'posts:list' %}">Home </a></div> 
				<div class="nav-item col-md-2 {% block createactive %}{% endblock createactive %}"><a class="nav-link" href="{% url 'posts:create' %}">Create Post</a></div>
				<div class="nav-item col-md-1 {% block grafanaactive %}{% endblock grafanaactive %}"><a class="nav-link" href="{% url 'grafana' %}">Grafana </a></div> 

				{% if not request.user.is_authenticated %}
				<div class="col-md-6"></div>
				<div class="col-md-1 nav-item  mr-sm-2"><a class="nav-link" href="{% url 'login' %}">Login</a></div>
				<div class="col-md-1 nav-item"><a class="nav-link" href="{% url 'register' %}">Register</a></div>
				{% else %}
				<div class="col-md-6"></div>
				<div class="nav-item nav-link col-md-2 active">Hello {{request.user}}!</div>
				<div class="col-md-1 nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></div>
				{% endif %}
			</div>
		</nav>
		<br/>
		{% block headOfpage %} {% endblock headOfpage %}
		{% block content %}
		{% endblock content %}
	</div>
</body>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>
<script src="http://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script type="text/javascript">
      $(document).ready(function(){

        $(".content_markdown").each(function(){

            var content = $(this).text();
            var markedContent = marked(content);
            $(this).html(markedContent);
            
        })

        $(".post_detail_item img").each(function(){
            $(this).addClass("img-responsive");
        })

        var titleitem = $("#id_title");
        
        function setTitle(value) {
            $("#preview_title").text(value);
        }
        setTitle(titleitem.val());
        titleitem.keyup(function(){
            setTitle($(this).val());
        })

        var contentitem = $("#id_content");

        function setContent(value) {
            var markedContent = marked(value)
            $("#preview_content").html(markedContent);

            $("#preview_content img").each(function(){
                $(this).addClass('img-responsive');
            })
        }
        setContent(contentitem.val())

        contentitem.keyup(function() {
            var newcontent = $(this).val();
            setContent(newcontent);
        })

        $(".comment-reply-btn").click(function(event){
        	event.preventDefault();
        	$(this).parent().next(".comment-reply").fadeToggle();
        })
    })
  </script>
</script>
</html>

templates/comment_thread.html
{% extends "base.html" %}
{% load urlify %}
{% block head_title %} {{ obj.title}} | {{block.super}} {% endblock head_title %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
	<div class="col-sm-12" style="padding-left: 10%;">
	  <p class="mb-0">{{comment.content}}</p>
	  <footer class="blockquote-footer">By {{comment.user}} | {{comment.timestamp|timesince}} ago | {% if comment.children.count > 0 %} {{ comment.children.count}} Comment{% if comment.children.count > 1 %}s{% endif %}  {% endif %}</cite></footer>
	  <hr/>
	  {% for child_comment in comment.children %}
		<blockquote class="blockquote">
		  <p class="mb-0">{{child_comment.content}}</p>
		  <footer class="blockquote-footer">By {{child_comment.user}} | {{comment.timestamp|timesince}} ago </cite></footer>

		</blockquote>
	  {% endfor %}
	  	{% if request.user.is_authenticated %}
		<form method="POST" action=".">{% csrf_token %}
			{{form|crispy}}
			<input type="hidden" name="parent_id" value="{{comment.id}}">
			<input type="submit" name="" value="Reply" class="btn btn-default">
		</form>
		{% else %}
		<p>You must login to reply</p>
		{% endif %}
	</div>
</div>
{% endblock content %}

templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block createactive %}active {% endblock createactive %}
{% block headOfpage %}<!--  Create a Post --> {% endblock headOfpage %}
{% block head_extra %} {{form.media}} {% endblock head_extra %}
{% block content %}
<!-- {{ block.super }} -->
<div class="row">
	<div class="col-md-2"></div>
<div class="col-md-8">
	<h1>{{title}}</h1>
	<hr/>
	<form method="POST" action='' enctype="multipart/form-data">{% csrf_token %}
		{{form|crispy}}
		<input class="btn btn-default centre" type="submit" name="{{title}}">
	</form>
</div>
</div>
{% endblock content %}

templates/grafana.html
{% extends "base.html" %}
{% block grafanaactive %} active{% endblock grafanaactive %}
{% block headOfpage %}<!--  {{title}} --> {% endblock headOfpage %}
{% block content %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript">
	function login_grafana() {
		console.log("Hey");
		var xhttp = new XMLHttpRequest();
		xhttp.onreadystatechange = function() {
			if( this.status == 200){
				// document.getElementById("demo").innerHTML = this.responseText;
				// document.getElementById("grafana").innerHTML = this.responseText;
				var binaryData = [];
				binaryData.push(this.response);
				var data_url = window.URL.createObjectURL(new Blob(binaryData, {type: "text/html"}));
				// var data_url = URL.createObjectURL(this.response);
				// console.log(this.response)
      			document.querySelector('#grafana').src = data_url;
			} else {
				console.error("errorssss");
			}
		};
		xhttp.open("GET","http://admin:admin@10.0.0.134/d/915Kgn9iz/node-exporter-full?refresh=5s&orgId=1&panelId=77&fullscreen&from=1550740512118&to=1550826912119&var-job=CIT&var-node=10.0.0.201&var-port=9100");
		// xhttp.setRequestHeader("X-WEBAUTH-NAME","admin")
		// xhttp.setRequestHeader("X-WEBAUTH-NAME","admin@stackuptech.com")
		// xhttp.setRequestHeader("Access-Control-Allow-Origin","allow");
		// xhttp.setRequestHeader("Access-Control-Allow-Method","GET, POST, OPTIONS, PUT, DELETE")
		// xhttp.setRequestHeader("Access-Control-Allow-Credentials","true");
		// xhttp.setRequestHeader("Access-Control-Allow-Headers","Authorization,Origin,Content-Type,Accept");
		// xhttp.setRequestHeader("Authorization","Bearer eyJrIjoiZDdpN00wZUtxRlVoUzRoeXpIR2F5eHhrUkw2ZXdqUXgiLCJuIjoia2V5IiwiaWQiOjF9");// + window.btoa("admin:admin"));
		xhttp.send();
	}
</script>
<div class="container">
	<button onclick="login_grafana()">Login</button>
	<p id="demo"></p>
	<div class="row">

		<!-- <iframe id="grafana" src="http://admin:admin@10.0.0.134/d/915Kgn9iz/node-exporter-full?refresh=5s&orgId=1&panelId=77&fullscreen&from=1550740512118&to=1550826912119&var-job=CIT&var-node=10.0.0.201&var-port=9100" width="1000px"sandbox="allow-forms allow-popups allow-same-origin allow-scripts"  height="800px" align="middle"></iframe> -->
		<div class="col-md-12">
			<iframe src="https://10.0.0.43:3000/d-solo/IKua5priz/node-exporter-full?orgId=1&refresh=5s&panelId=77&theme=light" width="450" height="200" frameborder="0"></iframe>
			<iframe src="https://10.0.0.43:3000/d-solo/IKua5priz/node-exporter-full?orgId=1&refresh=5s&panelId=78&theme=light" width="450" height="200" frameborder="0"></iframe>
		</div>
		<div class="col-md-12">
			<iframe src="https://10.0.0.43:3000/d-solo/IKua5priz/node-exporter-full?orgId=1&refresh=5s&panelId=60&theme=light" width="450" height="200" frameborder="0"></iframe>
			<iframe src="https://10.0.0.43:3000/d-solo/IKua5priz/node-exporter-full?orgId=1&refresh=5s&panelId=9&theme=light" width="450" height="200" frameborder="0"></iframe>
		</div>

	</div>
</div>

<script type="text/javascript">
	// $(document).ready(function() {

	//     $("#grafana").submit(function(e) {
	//     	e.preventDefault();
			// $.ajax(
		 //    {
		 //    	// console.log("Before geafa");
		 //      type: 'GET',
		 //      url: 'http://admin:admin@10.0.0.134/dashboard/db/node-exporter-full',
		 //      contentType: 'application/json',
		 //       xhrFields: {
			//         withCredentials: false
			//     },
		 //      // beforeSend: function(xhr, settings) {
		 //      //   xhr.setRequestHeader(
		 //      //     'Authorization', 'Basic ' + window.btoa('admin:admin')
		 //      //   );
		 //      // },
		 //      success: function(data) {
		 //        // $('#grafana').attr('src', 'http://admin:admin@10.0.0.134/dashboard/db/node-exporter-full');
		 //        // $('#grafana').contents().find('html').html(data);
		 //      //   var iframeDoc = $("#grafana").get(0).contentDocument;
			//      // iframeDoc.open();
			//      // iframeDoc.write(data);
			//      // iframeDoc.close();
		 //      }
		 //    }
		 //  );
	//	});
//	}
</script>
{% endblock content %}

templates/message_display.html
{% if messages %}
	<div name="message">
			<ul class="messages">
			{% for message in messages %}
				<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
			</ul>
	</div>
{% endif %}

templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block createactive %}active {% endblock createactive %}
{% block headOfpage %} Create a Post {% endblock headOfpage %}
{% block head_extra %} {{form.media}} {% endblock head_extra %}
{% block content %}
<!-- {{ block.super }} -->
<div class="row">
<div class="col-sm-5" style="padding: 2%;">
	<form method="POST" action='' enctype="multipart/form-data">{% csrf_token %}
		{{form|crispy}}
		<!-- <input type="text" name="title"/>
		<input type="textarea" name="content"/>
		<input type="file" name="image" accept="image/*" /> -->
		<input class="btn btn-default centre" type="submit" name="createPost">
	</form>
</div>
<div class="col-sm-2"></div>
<div class="col-sm-5" style="padding: 2%;">
	<!-- <h3>Form</h3> -->
	<h3>Preview</h3>
	<div class="content_preview">
		<h3 id="preview_title"></h3>
		<p id="preview_content"></p>
	</div>
</div>
</div>
{% endblock content %}